#let blog-tags = (
  programming: "Programming",
  software: "Software",
  network: "Network",
  software-engineering: "Software Engineering",
  tooling: "Tooling",
  linux: "Linux",
  dev-ops: "DevOps",
  compiler: "Compiler",
  music-theory: "Music Theory",
  tinymist: "Tinymist",
  golang: "Golang",
  typst: "Typst",
  life: "Life",
  misc: "Miscellaneous",
  ue5: "UE5",
  protobuf: "Protobuf",
  cloudflare: "Cloudflare",
  ai: "AI",
  astro: "Astro",
  blog: "Blog",
  creator: "Creator",
  design: "Design",
  tech: "Tech",
  theme: "Theme",
  toy: "Toy",
  puzzle: "Puzzle",
  vue: "Vue",
  vitepress: "Vitepress",
  vision-pro: "Vision Pro",
  writing: "Writing",
  mmo: "MMO",
  server: "Server",
  rust: "Rust",
  game: "Game",
  elixir: "Elixir",
  clang: "Clang",
  ml: "Machine Learning",
  python: "Python",
  tensorflow: "TensorFlow",
  algorithm: "Algorithm",
  apple: "Apple",
  ghost: "Ghost",
  windows: "Windows",
  wsl: "WSL",
  git: "Git",
  notion: "Notion",
  emacs: "Emacs",
  haskell: "Haskell",
  xr: "XR",
)

#let blog-collections = (
  blog: "Blog",
  essay: "Essay",
  project: "Project",
  note: "Note",
)
